= doxygen2adoc

Does what it says on the tin.

== Examples
Some examples of multi-language usage from our SDKs at https://teak.io[Teak].
Each SDK builds its docs using doxygen and doxygen2adoc in various languages using
configurations and appropriate partial templates.

* https://github.com/GoCarrot/teak-ios/tree/pw/doxygen[teak-ios] Objective C
* https://github.com/GoCarrot/teak-android/tree/pw/doxygen[teak-android] Java
* https://github.com/GoCarrot/teak-unity/tree/pw/doxygen[teak-unity] C#

The generated docs can be found at: http://docs.gocarrot-dev.com

== Errors

If you see:

  Found __deprecated as a parameter declname, check Doxygen config.

Then Doxygen is parsing an Objective C method such as:

  (void)identifyUser:(nonnull NSString*)userId withOptOutList:(nonnull NSArray*)optOut __deprecated;

And treating ``__deprecated`` as the name of the parameter. To fix this, use a
macro such as:

  (void)identifyUser:(nonnull NSString*)userId withOptOutList:(nonnull NSArray*)optOut __deprecated_msg("Use identifyUser:withConfiguration: instead");

Then add the following to your Doxygen config

  ENABLE_PREPROCESSING   = YES
  MACRO_EXPANSION        = YES
  EXPAND_ONLY_PREDEF     = YES
  PREDEFINED             = __deprecated_msg(x)=
